# Generated by Django 3.1.7 on 2021-09-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=300, verbose_name='Apellido')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('direc', models.CharField(max_length=300, verbose_name='Direccion')),
                ('loc', models.CharField(max_length=300, verbose_name='Localidad')),
                ('pcia', models.CharField(choices=[('C.A.B.A.', 'C.A.B.A.'), ('Buenos Aires', 'Buenos Aires'), ('Catamarca', 'Catamarca'), ('Chaco', 'Chaco'), ('Chubut', 'Chubut'), ('Córdoba', 'Córdoba'), ('Corrientes', 'Corrientes'), ('Entre Ríos', 'Entre Ríos'), ('Formosa', 'Formosa'), ('Jujuy', 'Jujuy'), ('La Pampa', 'La Pampa'), ('La Rioja', 'La Rioja'), ('Mendoza', 'Mendoza'), ('Misiones', 'Misiones'), ('Neuquén', 'Neuquén'), ('Río Negro', 'Río Negro'), ('Salta', 'Salta'), ('San Juan', 'San Juan'), ('Santa Cruz', 'Santa Cruz'), ('Santa Fe', 'Santa Fe'), ('Santiago del Estero', 'Santiago del Estero'), ('Tierra del Fuego', 'Tierra del Fuego'), ('Tucumán', 'Tucumán')], max_length=300, verbose_name='Provincia')),
                ('tlf', models.IntegerField(verbose_name='Telefono')),
                ('transp', models.CharField(default='N/A', max_length=300, verbose_name='Trasporte')),
            ],
        ),
        migrations.CreateModel(
            name='TituloPag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo de Pag')),
            ],
        ),
    ]
